name: AxGraves
version: '${project.version}'
main: com.artillexstudios.axgraves.AxGraves
api-version: '1.18'
folia-supported: true

permissions:
  axgraves.help:
    default: true
  axgraves.reload:
    default: op
  axgraves.list:
    default: true
  axgraves.list.other:
    default: op
  axgraves.tp:
    default: op
  axgraves.tp.bypass:
    default: op
  axgraves.allowgraves:
    default: true
  axgraves.limit.1:
    default: false